const db = require('./index.js');

const cities = [
  {
    name: 'Tel Aviv',
    fun: '95%',
    safety: '70%',
    queervibes: '100%',
    weather: '61F',
    description: 'This vibrant city is an undisputed queer capital of the Middle East, It offers a 24/7 non-stop activities, all year round great weather, great food, gay beaches and infinite of gay bars and night clubs. Every June Tel Aviv is celebrating the Gay Pride week, week of celebrations and happenings throughout the city with Pride Expo (Gay Culture Fair), LGBT Theater festival, LGBT Film Festival and the famous Pride Parade which is one of the most colorful gay parades in the world.',
    places: [],
  },
  {
    name: 'Berlin',
    fun: '100%',
    safety: '80%',
    queervibes: '99%',
    weather: '36F',
    description: 'It is pretty much a non-stop party, from the saunas, darkrooms, bars, clubs, cafés, festivals, balls, carnivals and celebrations a hedonist’s paradise, a sensualist’s haven, an aesthete’s delight and a raver’s Mecca, all in one package. The party scene is so diverse and innovative and celebrates any fetish! That is the reason fort the Folsom Europe fair in September and the Lesbian and Gay City Festival every June, Europe’s largest street party of its kind, being held in the traditional gay area around Nollendorfplatz in Schöneberg since 1993.',
    places: [],
  },
  {
    name: 'New York City',
    fun: '100%',
    safety: '80%',
    queervibes: '70%',
    weather: '19F',
    description: 'You can choose from endless variations on gay bars and clubs: from muscle mary clubs to cabaret piano bars, local intimate bars to trendy gay lounges. On Manhattan the gay scene is concentrated in a couple of neighborhoods. In Greenwhich Village lays the origin of gay pride, where the Stonewall riots in Christopher Street awakened gay emancipation. The new gay hot spot is Hell’s Kitchen, full trendy gay bars, restaurants and clubs. Chelsea neighborhood also offers a wide selection of gay venues concentrated around 8th Avenue.',
    places: [
      {
        name: 'Diner',
        address: '85 Broadway, Brooklyn, NY 11249',
        website: 'http://dinernyc.com/',
        vibe: '90\'s kid',
        queerdar: 2,
        description: 'Retro railcar environs & seasonal New American eats draw cool sorts to this funky spin on the diner.',
        lat: 40.710755,
        lng: -73.965555,
        category: 'Restaurant',
        identity: ['LGBTQIA+'],
        city: 'NYC',
        image: 'https://s3-us-west-1.amazonaws.com/queertrip/diner.jpg',
      },
      {
        name: 'Big Gay Ice Cream Shop',
        address: '125 E 7th St, New York, NY 10009',
        website: 'http://biggayicecream.com	',
        vibe: 'fluro family fun',
        queerdar: 1,
        description: 'Founded by Brooklynites Doug Quint and his partner, Bryan Petroff, this colorful, unicorn-emblazoned soft-serve shop is known for cheeky cones like the Salty Pimp and the Dorothy, as well as decadent shakes served in rainbow cups.',
        lat: 40.726502,
        lng: -73.984165,
        category: 'Restaurant',
        identity: ['LGBTQIA+', 'Gay'],
        city: 'NYC',
        image: 'https://s3-us-west-1.amazonaws.com/queertrip/big-gay.jpg',
      },
      {
        name: 'MeMe\'s Diner',
        address: '657 Washington Ave., Brooklyn',
        website: 'https://www.memesdiner.com/',
        vibe: 'retro',
        queerdar: 2,
        description: 'Book it to this proudly LGBTQ-owned-and-run diner, stat. A backyard garden is slated to open this summer, making the beloved Brooklyn restaurant even lovelier.',
        lat: 40.677839,
        lng: -73.963555,
        category: 'Restaurant',
        identity: ['LGBTQIA+'],
        city: 'NYC',
        image: 'https://s3-us-west-1.amazonaws.com/queertrip/meme.jpg',
      },
      {
        name: 'Henrietta Hudson',
        address: '438 Hudson St, New York, NY, 10014',
        website: 'http://henriettahudson.com',
        vibe: 'Mature',
        queerdar: 3,
        description: 'The oldest brick and mortar queer women’s bar in New York City',
        lat: 40.731209,
        lng: -74.006513,
        category: 'Bar',
        identity: ['Lesbian'],
        city: 'NYC',
        image: 'https://s3-us-west-1.amazonaws.com/queertrip/Henrietta.jpg',
      },
      {
        name: 'The Stonewall Inn',
        address: '53 Christopher St, New York, NY 10014',
        website: 'http://thestonewallinnnyc.com',
        vibe: 'Historical, all ages',
        queerdar: 3,
        description: 'The site of the Stonewall Riots that sparked the modern LGBTQ rights movement in the U.S',
        lat: 40.734044,
        lng: -74.002152,
        category: 'Bar',
        identity: ['LGBTQIA+'],
        city: 'NYC',
        image: 'https://s3-us-west-1.amazonaws.com/queertrip/StonewallInn.jpeg',
      },
      {
        name: 'Cubby Hole',
        address: '281 W 12th St, New York, NY 10014',
        website: 'http://www.cubbyholebar.com/',
        vibe: 'Eclectic',
        queerdar: 3,
        description: 'Lesbian or not, you\'ll undoubtedly find yourself freaking out with excitement when your song finally rolls into rotation on the jukebox in this colorful, tiny space. Apparently there\'s free popcorn, too.',
        lat: 40.737842,
        lng: -74.003763,
        category: 'Bar',
        identity: ['Lesbian'],
        city: 'NYC',
        image: 'https://s3-us-west-1.amazonaws.com/queertrip/cubbyhole.jpg',
      },
    ],
  },
  {
    name: 'San Francisco',
    fun: '90%',
    safety: '80%',
    queervibes: '80%',
    weather: '54F',
    description: 'Castro is one of the first gay neighborhoods in the United States. it remains one of the most prominent symbols of LGBT activism and events in the world. LGBT life here is not limited to the Castro neighborhood, though that’s a tourist draw for good reason — it’s a queer Disneyland. San Francisco is home to more nightlife than you can shake a go-go boy at, as well as vibrant bear and transexual communities. If you’re gay, chances are you’ve either been to San Francisco or plan to sometime in your life. It is Gay Mecca after all. Recent population demographics indicate that more than 15% of the population of San Francisco is gay and here are even more drag queens per square foot than anywhere else in the world.',
    places: [],
  },
  {
    name: 'Amsterdam',
    fun: '90%',
    safety: '90%',
    queervibes: '70%',
    weather: '39F',
    description: '',
    places: [],
  },
  {
    name: 'Barcelona',
    fun: '100%',
    safety: '80%',
    queervibes: '80%',
    weather: '39F',
    description: '',
    places: [],
  },
  {
    name: 'São Paulo',
    fun: '100%',
    safety: '80%',
    queervibes: '60%',
    weather: '39F',
    description: 'Especially noteworthy for LGBT travelers is the fact that São Paulo hosts the biggest gay pride celebration on the planet. São Paulo’s first Gay Pride was in 1997 and attracted only 2000 people. Nowadays, the carnival-like Gay Pride Parade draws nearly four million people who crowd onto the main boulevard of Paulista Avenue and the surrounding streets. Gay nightclubs feature a wide variety of shows, with drag, male strip-tease, singers, performances and some of the best DJs anywhere. There are plenty of bathhouses and sex clubs too, often with bars and show nights as well.',
    places: [],
  },
];

cities.forEach((city) => {
  db.save(city, (res) => {
    console.log(res);
  });
});
