const sampleData = [
  {
    name: 'Diner',
    address: '85 Broadway, Brooklyn, NY 11249',
    website: 'http://dinernyc.com/',
    vibe: '90\'s kid',
    queerdar: 2,
    description: 'Retro railcar environs & seasonal New American eats draw cool sorts to this funky spin on the diner.',
    lat: 40.710755,
    lng: -73.965555,
    category: 'Restaurant',
    identity: ['LGBTQIA+'],
    city: 'NYC',
    image: 'https://s3-us-west-1.amazonaws.com/queertrip/diner.jpg',
  },
  {
    name: 'Big Gay Ice Cream Shop',
    address: '125 E 7th St, New York, NY 10009',
    website: 'http://biggayicecream.com	',
    vibe: 'fluro family fun',
    queerdar: 1,
    description: 'Founded by Brooklynites Doug Quint and his partner, Bryan Petroff, this colorful, unicorn-emblazoned soft-serve shop is known for cheeky cones like the Salty Pimp and the Dorothy, as well as decadent shakes served in rainbow cups.',
    lat: 40.726502,
    lng: -73.984165,
    category: 'Restaurant',
    identity: ['LGBTQIA+', 'Gay'],
    city: 'NYC',
    image: 'https://s3-us-west-1.amazonaws.com/queertrip/big-gay.jpg',
  },
  {
    name: 'MeMe\'s Diner',
    address: '657 Washington Ave., Brooklyn',
    website: 'https://www.memesdiner.com/',
    vibe: 'retro',
    queerdar: 2,
    description: 'Book it to this proudly LGBTQ-owned-and-run diner, stat. A backyard garden is slated to open this summer, making the beloved Brooklyn restaurant even lovelier.',
    lat: 40.677839,
    lng: -73.963555,
    category: 'Restaurant',
    identity: ['LGBTQIA+'],
    city: 'NYC',
    image: 'https://s3-us-west-1.amazonaws.com/queertrip/meme.jpg',
  },
  {
    name: 'Henrietta Hudson',
    address: '438 Hudson St, New York, NY, 10014',
    website: 'http://henriettahudson.com',
    vibe: 'Mature',
    queerdar: 3,
    description: 'The oldest brick and mortar queer women’s bar in New York City',
    lat: 40.731209,
    lng: -74.006513,
    category: 'Bar',
    identity: ['Lesbian'],
    city: 'NYC',
    image: 'https://s3-us-west-1.amazonaws.com/queertrip/Henrietta.jpg',
  },
  {
    name: 'The Stonewall Inn',
    address: '53 Christopher St, New York, NY 10014',
    website: 'http://thestonewallinnnyc.com',
    vibe: 'Historical, all ages',
    queerdar: 3,
    description: 'The site of the Stonewall Riots that sparked the modern LGBTQ rights movement in the U.S',
    lat: 40.734044,
    lng: -74.002152,
    category: 'Bar',
    identity: ['LGBTQIA+'],
    city: 'NYC',
    image: 'https://s3-us-west-1.amazonaws.com/queertrip/StonewallInn.jpeg',
  },
  {
    name: 'Cubby Hole',
    address: '281 W 12th St, New York, NY 10014',
    website: 'http://www.cubbyholebar.com/',
    vibe: 'Eclectic',
    queerdar: 3,
    description: 'Lesbian or not, you’ll undoubtedly find yourself freaking out with excitement when your song finally rolls into rotation on the jukebox in this colorful, tiny space. Apparently there\'s free popcorn, too.',
    lat: 40.737842,
    lng: -74.003763,
    category: 'Bar',
    identity: ['Lesbian'],
    city: 'NYC',
    image: 'https://s3-us-west-1.amazonaws.com/queertrip/cubbyhole.jpg',
  },
  // {
  // name: ,
  // address: ,
  // website: ,
  // vibe: ,
  // queerdar: ,
  // description: ,
  // lat: ,
  // lng: ,
  // category: ,
  // identity: ,
  // city: ,
  // },
  // {
  //   name: ,
  //   address: ,
  //   website: ,
  //   vibe: ,
  //   queerdar: ,
  //   description: ,
  //   lat: ,
  //   lng: ,
  //   category: ,
  //   identity: ,
  //   city: ,
  // },
  // {
  //   name: ,
  //   address: ,
  //   website: ,
  //   vibe: ,
  //   queerdar: ,
  //   description: ,
  //   lat: ,
  //   lng: ,
  //   category: ,
  //   identity: ,
  //   city: ,
  // },
  // {
  //   name: ,
  //   address: ,
  //   website: ,
  //   vibe: ,
  //   queerdar: ,
  //   description: ,
  //   lat: ,
  //   lng: ,
  //   category: ,
  //   identity: ,
  //   city: ,
  // },
  // {
  //   name: ,
  //   address: ,
  //   website: ,
  //   vibe: ,
  //   queerdar: ,
  //   description: ,
  //   lat: ,
  //   lng: ,
  //   category: ,
  //   identity: ,
  //   city: ,
  // },
];

export default sampleData;
